name: Build firmware and disk images
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Enable containerd image store
      run: |
        sudo sh -c "echo '{ \"features\": { \"containerd-snapshotter\": true } }' > /etc/docker/daemon.json"
        sudo systemctl restart docker
    - name: Install dependencies
      run: make deps
    - name: Build Alpine Generic x64 target
      run: make alpine-x64-release
    - name: Build Alpine Raspberry Pi target
      run: make alpine-rpi-release
    - name: Build Alpine Orange Pi One target
      run: make alpine-orangepi-one-release
    - uses: actions/upload-artifact@v4
      with:
        path: release
